# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-05 05:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.FileField(upload_to='./audio/')),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
                ('text3', models.TextField()),
                ('text4', models.TextField()),
                ('text5', models.TextField()),
                ('text6', models.TextField()),
                ('text7', models.TextField()),
            ],
        ),
    ]
